# Generated by Django 3.2.9 on 2021-11-24 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
