# Generated by Django 3.2.9 on 2021-11-24 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_folders_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('folders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folders')),
            ],
        ),
    ]
