# Generated by Django 3.2.9 on 2021-11-24 09:49

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_subfolders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('uploaded_by', models.CharField(max_length=35)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='file/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField()),
                ('trash', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
    ]
