# Generated by Django 3.2.9 on 2021-12-01 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfolders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
        ),
    ]
